name: pose
channels:
  - defaults
dependencies:
  - ca-certificates=2025.12.2=hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=24.2=py38hca03da5_0
  - python=3.8.20=hb885b13_0
  - readline=8.3=h0b18652_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.44.0=py38hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.3
      - filelock==3.14.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - mmpose==1.3.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - munkres==1.1.4
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pycocotools==2.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.10.1
      - setuptools==58.0.4
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - tomli==2.3.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /opt/anaconda3/envs/pose
